# install.packages(c("corrplot","forestplot","ggplot2","gplots","knitr","knitrProgressBar","mgcv","openxlsx","plotROC","plyr","pROC","RColorBrewer","reshape2","rmarkdown","viridis","HDInterval","doParallel","viridis"))
library(rmarkdown)
knitr::opts_knit$set(dev = "svg")
options(warn = 1, bitmapType = "cairo")
render("allsample_demographics.Rmd")
render("polygenic_scores.Rmd")
render("common_variants.Rmd")
render("rare_variants.Rmd")
render("somatic_variants.Rmd")
